### PR TITLE
Remove use of relying on exceptions as control flow when reading an input stream

### LINKED ISSUE #24: CommandManager uses exceptions as control flow when loading a save game
I am running the game in a debug mode while attached to Visual Studio debugger in order to be able to catch any exceptions.

It looks like the implementation of `CommandManager::load()` which uses the `FileStream` object utilizes exception handling to implement control flow in order to know when the save file has finished loading.

This causes a debugger break every time when attempting to load a save game, breaking developer debugging cycle.

See 

image

and its caller function

image

I think it would be preferable to avoid this kind of a `while(true)` loop + throwing `eof` exceptions when interacting with `FileStream`, and instead have an API that queries the length of the file, and then loop until that end of file has been reached.

That would ease running the game with a debugger attached.

Not overly a big problem, though just thought to write down as to not lose any observations. I might propose a PR if you agree with the direction @henricj ?

### PR DESCRIPTION
**Pull request by juj**
Remove use of relying on exceptions as control flow when reading an input stream. Closes #24.

This eases running the game while having a debugger attached that catches on all thrown exceptions.

### CODE REVIEW

File: include/Network/ENetPacketIStream.h [hunk 1]
```diff
@@ -39,6 +39,8 @@ class ENetPacketIStream final : public InputStream {
         }
     }
 
+    long bytesLeft() const override { return packet->dataLength - currentPos; }
```
Comment (henricj) [inline include/Network/ENetPacketIStream.h:42]: Can serialized data cross packet boundaries?  If so, we might want a sentinel value (e.g., "-1") or some-such to indicate an unknown stream size that would fall back to the old behavior (read until exception).

Comment (juj) [reply include/Network/ENetPacketIStream.h:42]: > Can serialized data cross packet boundaries? 

My impression is that it would not.

Even if it does, the behavior should be identical here to how it worked before, with the only exception that line https://github.com/henricj/dunelegacy/pull/34/files#diff-1ec625d8f6a9012cde14119737e7a5b614f5ec6b750d954519ac794f2792fdb1R67 will now print a newly added warning message.

So if there is data serialization, then that warning message will begin to print - in which case after identifying that, the warning message could be removed, and a comment be put in place instead that says that such behavior is to be expected.

For save game loading from disk and from memory buffers though, it's good to have some kind of warning at least if reading malformed input data. Though the read API there does not seem to have a way to distinguish between these two currently.
